### ISSUE TITLE
Integration with OpenSpiel

### ISSUE THREAD

**Issue by michalsustr** [facebookresearch/rebel#1]
Since ReBeL uses C++/Python, have you thought about using [OpenSpiel](https://github.com/deepmind/open_spiel)? Factored observations (public+private observations) and public states have been introduced recently, as well as libtorch. A structured representation of observations [has just been published](https://github.com/deepmind/open_spiel/commit/2b5e4f570c119cbdf0dd856e19dcbea9c351cc22). I didn't look at the code of ReBeL in details so I am not sure how much work that would be. It would be awesome if it was easy to compare and develop algorithms in the same opensource codebase. The advantage is that you can then run the algorithm easily on other games -- there's currently about 50 of them.

**Comment by akhti** [comment]
Hi Michal! We considered using OpenSpiel, but decided against it due to lack of torch integration and information about the dimensionality of the belief space. The latter is required as ReBeL operates on public belief states instead of public states.

**Comment by michalsustr** [comment]
Oh ok, cool! I am adding [public state API](https://github.com/deepmind/open_spiel/tree/master/open_spiel/public_states) to OpenSpiel. It is largely a work-in-progress. I'm happy to chat about it if you're interested -- feel free to reach out by e-mail.

**Comment by kendonB** [comment]
@michalsustr @akhti is this integration possible now?
