### ISSUE TITLE
average strategy calculation

### ISSUE THREAD

**Issue by lilith829** [facebookresearch/rebel#17]
Hi,

Great work. I really enjoyed reading the paper. I have two questions about the implementation.

(1) I don't understand how the average strategy is calculated.
In the paper, 
![image](https://user-images.githubusercontent.com/79941943/111727018-49e86080-8827-11eb-9808-a6fb84843683.png)
In the code, 
![image](https://user-images.githubusercontent.com/79941943/111727075-700e0080-8827-11eb-83ee-2c80787ccfc6.png)
I can see that strat_discount corresponds to t/(t+1), but I don't understand why the last strategies don't need to multiply by 1/(t+1).

(2) when linear_update is used, alpha = 2 / (t + 2).
![image](https://user-images.githubusercontent.com/79941943/111727359-faeefb00-8827-11eb-9c50-64f02ebeb9d7.png)

I thought the discount value should be t/(t+2). But the code shows this.
![image](https://user-images.githubusercontent.com/79941943/111727480-325da780-8828-11eb-93c3-973aa1283c45.png)

**Comment by akhti** [comment]
1. Let assume that at step `t` `sum_strategies` hold `\overline{\pi} / t`. Then to get sum_strategies of the same kind for the next step, one has to do ` ((sum_strategies * t) +  (t + 1) * last_strategies) / (t + 1)`. Here we go from `sum_strategies` to  `\overline{\pi} `, then apply the step of linear update, and go back to multiplied sum strategies. Simplifying the expression, we get `sum_strategies  * (t / (t + 1)) + last_strategies`.

2. Is similar. Note that `alpha` is applied to a diff of regret vs mean, not to the new regret.
