### ISSUE TITLE
90 DGX-1's for data generation?

### ISSUE THREAD

**Issue by zhaoyin214** [facebookresearch/rebel#22]
in the paper of rebel, it is reported that 90 DGX-1's are used.

could you tell me some details in training such as how many DGX-1's are used for training and how many for data generation? how long the training takes. for training a mlp containing 6 hidden layers with 1536 units each, it is hard to image why such a huge number of gpus is needed.

**Comment by brewer-b** [comment]
I believe the paper stated that one gpu was used for training.

**Comment by akhti** [comment]
Indeed, one GPU was used for training.
To generate a single data point we need to run CFR in a subgame. For this we need to evaluate the value net in each leaf node on each iteration. That's why data generation is orders of magnitude more expensive than training.
