### ISSUE TITLE
vector.reserve() usage

### ISSUE THREAD

**Issue by diditforlulz273** [facebookresearch/rebel#29]
https://github.com/facebookresearch/rebel/blob/452c837ab7e0f59d5e7c969f4595e2f5d4c166ae/csrc/liars_dice/tree.h#L61

This trick looks quite smart but in fact it cripples the performance of unroll_tree() by at least 10 times(I kinda tested it on 'other-card-game' trees).
push_back() does reserve additional memory for the vector each time it gets close to the end, but it does it in ~2x amount of the vector, so without manual reserve() you have it in an exponential way with chunks getting bigger and bigger, calling malloc way less often.
Calling reserve() manually here gets you to performing malloc() every damn new non-terminal node :)

**Comment by akhti** [comment]
Indeed, good catch!
