### ISSUE TITLE
Link errors on OS X 

### ISSUE THREAD

**Issue by ggzzz** [facebookresearch/rebel#3]
I get following output when compiling the code on OS X, it seems that some link errors occurred:

➜  rebel git:(master) ✗ make
mkdir -p build && cd build && cmake ../csrc/liars_dice -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=../cfvpy && make -j
-- Found PythonInterp: /usr/local/miniconda3/bin/python (found version "3.7.2")
-- Found PythonInterp: /usr/local/miniconda3/bin/python (found suitable version "3.7.2", minimum required is "3.7")
-- pybind11 v2.3.dev1
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/rebel/build
make[1]: Entering directory '/Users/user/rebel/build'
make[2]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
[  7%] Built target gtest
make[3]: Entering directory '/Users/user/rebel/build'
[ 15%] Built target _rela
[ 38%] Built target liars_dice_lib
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
[ 46%] Built target gtest_main
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
[ 50%] Linking CXX executable recursive_eval
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Leaving directory '/Users/user/rebel/build'
[ 53%] Linking CXX shared module /Users/user/rebel/cfvpy/rela.cpython-37m-darwin.so
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
make[3]: Entering directory '/Users/user/rebel/build'
[ 57%] Linking CXX executable liar_tree_test
[ 61%] Linking CXX executable liar_recursive_solving_test
make[3]: Entering directory '/Users/user/rebel/build'
[ 65%] Linking CXX executable liar_game_test
[ 69%] Linking CXX executable liar_subgame_solving_test
[ 73%] Linking CXX executable gen_benchmark
ld: in section __TEXT,__text reloc 11: length != 2 and X86_64_RELOC_GOT not supported file 'CMakeFiles/liar_game_test.dir/liars_dice_test.cc.o' for architecture x86_64
ld: in section __TEXT,__text reloc 3: length != 2 and X86_64_RELOC_GOT not supported file 'CMakeFiles/liar_recursive_solving_test.dir/recursive_solving_test.cc.o' for architecture x86_64
ld: in section __TEXT,__text reloc 7: length != 2 and X86_64_RELOC_GOT not supported file 'CMakeFiles/liar_subgame_solving_test.dir/subgame_solving_test.cc.o' for architecture x86_64
ld: in section __TEXT,__text reloc 11: length != 2 and X86_64_RELOC_GOT not supported file 'CMakeFiles/liar_tree_test.dir/liars_dice_test.cc.o' for architecture x86_64
ld: in section __TEXT,__text reloc 24: length != 2 and X86_64_RELOC_GOT not supported file 'CMakeFiles/gen_benchmark.dir/gen_benchmark.cc.o' for architecture x86_64
ld: in section __TEXT,__text reloc 119: length != 2 and X86_64_RELOC_GOT not supported file 'CMakeFiles/recursive_eval.dir/recursive_eval.cc.o' for architecture x86_64
clang: clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)fatal error: linker command failed with exit code 1 (use -v to see invocation)
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)

make[3]: *** [CMakeFiles/liar_game_test.dir/build.make:89: liar_game_test] Error 1
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: *** [CMakeFiles/gen_benchmark.dir/build.make:88: gen_benchmark] Error 1
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: *** [CMakeFiles/liar_tree_test.dir/build.make:89: liar_tree_test] Error 1
make[3]: Leaving directory '/Users/user/rebel/build'
make[2]: *** [CMakeFiles/Makefile2:228: CMakeFiles/gen_benchmark.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:151: CMakeFiles/liar_game_test.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:190: CMakeFiles/liar_tree_test.dir/all] Error 2
make[3]: *** [CMakeFiles/liar_recursive_solving_test.dir/build.make:89: liar_recursive_solving_test] Error 1
make[3]: Leaving directory '/Users/user/rebel/build'
make[3]: *** [CMakeFiles/liar_subgame_solving_test.dir/build.make:89: liar_subgame_solving_test] Error 1
make[3]: Leaving directory '/Users/user/rebel/build'
make[2]: *** [CMakeFiles/Makefile2:379: CMakeFiles/liar_recursive_solving_test.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:112: CMakeFiles/liar_subgame_solving_test.dir/all] Error 2
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [CMakeFiles/recursive_eval.dir/build.make:87: recursive_eval] Error 1
make[3]: Leaving directory '/Users/user/rebel/build'
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/recursive_eval.dir/all] Error 2
ld: in libliars_dice_lib.a(subgame_solving.cc.o), in section __TEXT,__text reloc 7: length != 2 and X86_64_RELOC_GOT not supported for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [CMakeFiles/rela.dir/build.make:88: /Users/user/rebel/cfvpy/rela.cpython-37m-darwin.so] Error 1
make[3]: Leaving directory '/Users/user/rebel/build'
make[2]: *** [CMakeFiles/Makefile2:340: CMakeFiles/rela.dir/all] Error 2
make[2]: Leaving directory '/Users/user/rebel/build'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/Users/user/rebel/build'
make: *** [compile] Error 2

**Comment by akhti** [comment]
Sorry, we only support linux systems.

**Comment by yffbit** [comment]
@akhti 
The C codes also work on Windows. I have tested  it with Visual Studio 2017.
