### ISSUE TITLE
CFR Implementation

### ISSUE THREAD

**Issue by diditforlulz273** [facebookresearch/rebel#30]
Been bumbling around Rebel's code. Perhaps it's too late at night and I'm missing something, but shouldn't hand value propagated up for non-traverser node here:
https://github.com/facebookresearch/rebel/blob/452c837ab7e0f59d5e7c969f4595e2f5d4c166ae/csrc/liars_dice/subgame_solving.cc#L570

be multiplied by OP's action strategy in the node exactly as it happens here:
https://github.com/facebookresearch/rebel/blob/452c837ab7e0f59d5e7c969f4595e2f5d4c166ae/csrc/liars_dice/subgame_solving.cc#L556-L557

Even if we pretend we know nothing about OP's strategy(why?), we can not simply sum up all the child values - probably take any or calc a weighted average.

**Comment by brewer-b** [comment]
is the opponents strategy already accounted for when passing down the opponent reach probabilities?

**Comment by diditforlulz273** [comment]
You're right, it is just different in my CFR implementation, so I missed it here. Thanks, closing this then.
