### ISSUE TITLE
Issue importing a seemingly non existent file called cfvpy.rela

### ISSUE THREAD

**Issue by HJia42** [facebookresearch/rebel#33]
Hi, I was trying to follow the instructions to implement the rebel algorithm for self-play in Liar's Dice and got stuck on the step with running the following part of the instructions:

python run.py --adhoc --cfg conf/c02_selfplay/liars_sp.yaml \
    env.num_dice=1 \
    env.num_faces=4 \
    env.subgame_params.use_cfr=true \
    selfplay.cpu_gen_threads=60

in doing so I get the following issue

Traceback (most recent call last):
  File "run.py", line 25, in <module>
    import cfvpy.tasks
  File "/home/hjia/rebel/cfvpy/tasks.py", line 15, in <module>
    import cfvpy.selfplay
  File "/home/hjia/rebel/cfvpy/selfplay.py", line 27, in <module>
    import cfvpy.rela
ModuleNotFoundError: No module named 'cfvpy.rela'

I looked into that specific location and indeed there was no file called rela. Is there something I'm missing? Or does this file not exist?

**Comment by akhti** [comment]
This is ".so" file that should be compiled. Did you run `make`?

**Comment by KasparovGary** [comment]
Hello, I have also tried to install ReBeL following your instructions. Ended up receiving a lot of warnings and errors due to dependencies issues at compiling the C++ part using `make` or training a value net at Liar's Dice section.

**Comment by akhti** [comment]
could you provide more info regarding your conda environment and operating system?

**Comment by KasparovGary** [comment]
CONDA ENVIRONMENT INFO

(rebel) james@comp:~$ conda info

     active environment : rebel
    active env location : /home/USERS/james/.conda/envs/rebel
            shell level : 1
       user config file : /home/USERS/james/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.7=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /home/USERS/james/.conda/pkgs
       envs directories : /home/USERS/james/.conda/envs
                          /opt/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.15.0-46-generic ubuntu/20.04.5 glibc/2.31
                UID:GID : 5582:513
             netrc file : None
           offline mode : False

OPERATING SYSTEM

  System Version:	macOS 12.6 (21G115)
  Kernel Version:	Darwin 21.6.0
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,3
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	1,4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB

PD: I have also tried to run it on a server ending up with `make` compilation errors.

**Comment by HJia42** [comment]
When I run "make" I get the following error at the end:

mkdir -p build && cd build && cmake ../csrc/liars_dice -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=../cfvpy && make -j
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at /phddata/hjia/rebel/third_party/googletest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at /phddata/hjia/rebel/third_party/googletest/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at /phddata/hjia/rebel/third_party/googletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found PythonInterp: /phddata/hjia/miniconda3/envs/rebel/bin/python (found version "3.7.13")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PythonInterp: /phddata/hjia/miniconda3/envs/rebel/bin/python (found suitable version "3.7.13", minimum required is "3.7")
-- Found PythonLibs: /phddata/hjia/miniconda3/envs/rebel/lib/libpython3.7m.so (found suitable version "3.7.13", minimum required is "3.7")
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY)
CMake Warning at /phddata/hjia/miniconda3/envs/rebel/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:31 (message):
  Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
  or a Caffe2 dependent library, the next warning / error will give you more
  info.
Call Stack (most recent call first):
  /phddata/hjia/miniconda3/envs/rebel/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /phddata/hjia/miniconda3/envs/rebel/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:34 (find_package)


CMake Error at /phddata/hjia/miniconda3/envs/rebel/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:90 (message):
  Your installed Caffe2 version uses CUDA but I cannot find the CUDA
  libraries.  Please set the proper CUDA prefixes and / or install CUDA.
Call Stack (most recent call first):
  /phddata/hjia/miniconda3/envs/rebel/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:34 (find_package)

**Comment by HJia42** [comment]
I only installed this using "conda install cmake"

**Comment by HJia42** [comment]
Fi
