### ISSUE TITLE
Issues compiling make

### ISSUE THREAD

**Issue by HJia42** [facebookresearch/rebel#34]
Currently having issue with compiling and not sure what to do to fix them

rm -rf build cfvpy/rela*so
mkdir -p build && cd build && cmake ../csrc/liars_dice -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=../cfvpy && make -j
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at /home/hjia/rebel/third_party/googletest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at /home/hjia/rebel/third_party/googletest/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at /home/hjia/rebel/third_party/googletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Found PythonInterp: /home/hjia/anaconda3/envs/rebel/bin/python (found version "3.7.13")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found PythonInterp: /home/hjia/anaconda3/envs/rebel/bin/python (found suitable version "3.7.13", minimum required is "3.7")
-- Found PythonLibs: /home/hjia/anaconda3/envs/rebel/lib/libpython3.7m.so (found suitable version "3.7.13", minimum required is "3.7")
-- Found CUDA: /usr (found version "11.5")
-- Caffe2: CUDA detected: 11.5
-- Caffe2: CUDA nvcc is: /usr/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr
-- Caffe2: Header version is: 11.5
-- Found CUDNN: /home/hjia/anaconda3/envs/rebel/lib/libcudnn.so
-- Found cuDNN: v7.6.5  (include: /home/hjia/anaconda3/envs/rebel/include, library: /home/hjia/anaconda3/envs/rebel/lib/libcudnn.so)
-- Added CUDA NVCC flags for: -gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
CMake Warning (dev) at /home/hjia/anaconda3/envs/rebel/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/hjia/anaconda3/envs/rebel/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:122 (find_package_handle_standard_args)
  CMakeLists.txt:34 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found torch: /home/hjia/anaconda3/envs/rebel/lib/python3.7/site-packages/torch/lib/libtorch.so
-- Found PythonInterp: /home/hjia/anaconda3/envs/rebel/bin/python (found version "3.7.13")
-- Found PythonLibs: /home/hjia/anaconda3/envs/rebel/lib/libpython3.7m.so
-- pybind11 v2.3.dev1
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:37 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

	/home/hjia/rebel/csrc/liars_dice/liars_dice.cc
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:37 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

	/home/hjia/rebel/csrc/liars_dice/subgame_solving.cc
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:37 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

	/home/hjia/rebel/csrc/liars_dice/real_net.cc
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:37 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

	/home/hjia/rebel/csrc/liars_dice/recursive_solving.cc
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:37 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

	/home/hjia/rebel/csrc/liars_dice/stats.cc
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:41 (add_executable):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

	/home/hjia/rebel/csrc/liars_dice/recursive_eval.cc
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:60 (add_executable):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

	/home/hjia/rebel/csrc/liars_dice/gen_benchmark.cc
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at CMakeLists.txt:41 (add_executable):
  Cannot generate a safe runtime search path for target recursive_eval
  because files in some directories may conflict with libraries in implicit
  directories:

	runtime library [libcufft.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib
	runtime library [libcurand.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib

  Some of these libraries may not be found correctly.

CMake Warning at /home/hjia/rebel/third_party/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Cannot generate a safe runtime search path for target rela because files in
  some directories may conflict with libraries in implicit directories:

	runtime library [libcufft.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib
	runtime library [libcurand.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:57 (pybind11_add_module)

CMake Warning at CMakeLists.txt:60 (add_executable):
  Cannot generate a safe runtime search path for target gen_benchmark because
  files in some directories may conflict with libraries in implicit
  directories:

	runtime library [libcufft.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib
	runtime library [libcurand.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib

  Some of these libraries may not be found correctly.

CMake Warning at CMakeLists.txt:68 (add_executable):
  Cannot generate a safe runtime search path for target liar_game_test
  because files in some directories may conflict with libraries in implicit
  directories:

	runtime library [libcufft.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib
	runtime library [libcurand.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib

  Some of these libraries may not be found correctly.

CMake Warning at CMakeLists.txt:72 (add_executable):
  Cannot generate a safe runtime search path for target liar_tree_test
  because files in some directories may conflict with libraries in implicit
  directories:

	runtime library [libcufft.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib
	runtime library [libcurand.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib

  Some of these libraries may not be found correctly.

CMake Warning at CMakeLists.txt:76 (add_executable):
  Cannot generate a safe runtime search path for target
  liar_recursive_solving_test because files in some directories may conflict
  with libraries in implicit directories:

	runtime library [libcufft.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib
	runtime library [libcurand.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib

  Some of these libraries may not be found correctly.

CMake Warning at CMakeLists.txt:80 (add_executable):
  Cannot generate a safe runtime search path for target
  liar_subgame_solving_test because files in some directories may conflict
  with libraries in implicit directories:

	runtime library [libcufft.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib
	runtime library [libcurand.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  	/home/hjia/anaconda3/envs/rebel/lib

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/hjia/rebel/build
make[1]: Entering directory '/home/hjia/rebel/build'
make[2]: Entering directory '/home/hjia/rebel/build'
make[3]: Entering directory '/home/hjia/rebel/build'
make[3]: Entering directory '/home/hjia/rebel/build'
make[3]: Entering directory '/home/hjia/rebel/build'
make[3]: Leaving directory '/home/hjia/rebel/build'
make[3]: Leaving directory '/home/hjia/rebel/build'
make[3]: Leaving directory '/home/hjia/rebel/build'
make[3]: Entering directory '/home/hjia/rebel/build'
make[3]: Entering directory '/home/hjia/rebel/build'
make[3]: Entering directory '/home/hjia/rebel/build'
[  7%] Building CXX object CMakeFiles/_rela.dir/rela/types.cc.o
[  7%] Building CXX object CMakeFiles/liars_dice_lib.dir/subgame_solving.cc.o
[ 19%] Building CXX object CMakeFiles/liars_dice_lib.dir/liars_dice.cc.o
[ 19%] Building CXX object third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 19%] Building CXX object CMakeFiles/liars_dice_lib.dir/real_net.cc.o
[ 23%] Building CXX object CMakeFiles/liars_dice_lib.dir/recursive_solving.cc.o
[ 26%] Building CXX object CMakeFiles/liars_dice_lib.dir/stats.cc.o
/home/hjia/rebel/csrc/liars_dice/rela/types.cc: In static member function ‘static rela::ValueTransition rela::ValueTransition::fromVector(const std::vector<at::Tensor>&)’:
/home/hjia/rebel/csrc/liars_dice/rela/types.cc:53:19: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
   53 |   return std::move(result);
  	|      	~~~~~~~~~^~~~~~~~
/home/hjia/rebel/csrc/liars_dice/rela/types.cc:53:19: note: remove ‘std::move’ call
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [CMakeFiles/liars_dice_lib.dir/build.make:104: CMakeFiles/liars_dice_lib.dir/real_net.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 30%] Linking CXX static library ../../../lib/libgtest.a
make[3]: Leaving directory '/home/hjia/rebel/build'
[ 30%] Built target gtest
make[3]: Entering directory '/home/hjia/rebel/build'
make[3]: Leaving directory '/home/hjia/rebel/build'
make[3]: Entering directory '/home/hjia/rebel/build'
[ 34%] Building CXX object third_party/googletest/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 38%] Linking CXX static library ../../../lib/libgtest_main.a
make[3]: Leaving directory '/home/hjia/rebel/build'
[ 38%] Built target gtest_main
/home/hjia/rebel/csrc/liars_dice/rela/types.cc: In function ‘float readInt(FILE*)’:
/home/hjia/rebel/csrc/liars_dice/rela/types.cc:83:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   83 |   fread(&tmp, sizeof(int), 1, file);
  	|   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hjia/rebel/csrc/liars_dice/rela/types.cc: In static member function ‘static rela::ValueTransition rela::ValueTransition::load(FILE*, bool*)’:
/home/hjia/rebel/csrc/liars_dice/rela/types.cc:104:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  104 |   fread(&value_size, sizeof(int), 1, file);
  	|   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hjia/rebel/csrc/liars_dice/rela/types.cc:107:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  107 |   fread(result.query.data_ptr<float>(), sizeof(float), query_size, file);
  	|   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 42%] Linking CXX static library lib_rela.a
make[3]: Leaving directory '/home/hjia/rebel/build'
[ 42%] Built target _rela
make[3]: Leaving directory '/home/hjia/rebel/build'
make[2]: *** [CMakeFiles/Makefile2:168: CMakeFiles/liars_dice_lib.dir/all] Error 2
make[2]: Leaving directory '/home/hjia/rebel/build'
make[1]: *** [Makefile:146: all] Error 2
make[1]: Leaving directory '/home/hjia/rebel/build'
make: *** [Makefile:5: compile] Error 2

**Comment by cyberbyte53** [comment]
Hi!
How did u resolve it?
