### ISSUE TITLE
Training crashes with Python being out of memory

### ISSUE THREAD

**Issue by zorro-rgb** [facebookresearch/rebel#4]
Hi, I tried to run the training
```
python run.py --adhoc --cfg conf/c02_selfplay/liars_sp.yaml \
    env.num_dice=1 \
    env.num_faces=4 \
    env.subgame_params.use_cfr=true \
    selfplay.cpu_gen_threads=60
```

but after approx 45 minutes python runs out of memory on a 32GB machine (with some swap enabled):

[Mon Sep 21 19:01:30 2020] Out of memory: Kill process 92038 (python) score 975 or sacrifice child
[Mon Sep 21 19:01:30 2020] Killed process 92038 (python) total-vm:59949656kB, anon-rss:31843680kB, file-rss:91564kB, shmem-rss:12292kB

I suspect there is some memory leak, since the game it is trained on is tiny. Any ideas?

**Comment by akhti** [comment]
The default buffer size is pretty big it takes ~300Gb. Try using smaller buffer: `replay.capacity=20000`
