### ISSUE TITLE
Hydra dependency will not install - git@github.com:akhti/hydra.git

### ISSUE THREAD

**Issue by ivberg** [facebookresearch/rebel#5]
Linux Ubuntu 20.04:
>pip3 install -r requirements.txt
Obtaining hydra from git+git@github.com:akhti/hydra.git#egg=hydra (from -r requirements.txt (line 10))
  DEPRECATION: This form of VCS requirement is being deprecated: git+git@github.com:akhti/hydra.git#egg=hydra. pip 21.0 will remove support for this functionality. A possible replacement is git+https://git@example.com/..., git+ssh://git@example.com/..., or the insecure git+git://git@example.com/.... You can find discussion regarding this at https://github.com/pypa/pip/issues/7554.
  Cloning git@github.com:akhti/hydra.git to ./src/hydra
  Running command git clone -q git@github.com:akhti/hydra.git /home/ivberg/GitRepos/rebel/src/hydra
The authenticity of host 'github.com (140.82.114.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
  Warning: Permanently added 'github.com,140.82.114.3' (RSA) to the list of known hosts.
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
ERROR: Command errored out with exit status 128: git clone -q git@github.com:akhti/hydra.git /home/ivberg/GitRepos/rebel/src/hydra Check the logs for full command output.

Windows Win10 1809:
>pip install -r requirements.txt

Obtaining hydra from git+git@github.com:akhti/hydra.git#egg=hydra (from -r requirements.txt (line 10))
  DEPRECATION: This form of VCS requirement is being deprecated: git+git@github.com:akhti/hydra.git#egg=hydra. pip 21.0 will remove support for this functionality. A possible replacement is git+https://git@example.com/..., git+ssh://git@example.com/..., or the insecure git+git://git@example.com/.... You can find discussion regarding this at https://github.com/pypa/pip/issues/7554.
  Cloning git@github.com:akhti/hydra.git to .\src\hydra
  Running command git clone -q git@github.com:akhti/hydra.git 'c:\src\rebel\src\hydra'
  Host key verification failed.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
ERROR: Command errored out with exit status 128: git clone -q git@github.com:akhti/hydra.git 'c:\src\rebel\src\hydra' Check the logs for full command output.

**Comment by akhti** [comment]
@ivberg please pull and try again

**Comment by xgshark** [comment]
I am having similar issues. Ubuntu 20.04:

Cloning into '/home/code/projects/rebel/third_party/pybind11'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pybind/pybind11.git' into submodule path '/home/code/projects/rebel/third_party/pybind11' failed
Failed to clone 'third_party/pybind11'. Retry scheduled
Cloning into '/home/code/projects/rebel/third_party/pybind11'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pybind/pybind11.git' into submodule path '/home/code/projects/rebel/third_party/pybind11' failed
Failed to clone 'third_party/pybind11' a second time, aborting

**Comment by akhti** [comment]
@xgshark this is a different issue as you have error while cloning a public repo (pybind11).

Does it work when you try to clone it separately?
```
git clone git@github.com:pybind/pybind11.git
```

If not, something is very peculiar with your git config

**Comment by yffbit** [comment]
@xgshark 
you can try this:
```
rm -rf third_party/*
cd third_party
git clone https://github.com/google/googletest.git
git clone -b v2.3 https://github.com/pybind/pybind11.git
cd ..
```

**Comment by johnsyin** [comment]
> @xgshark
> you can try this:
> 
> ```
> rm -rf third_party/*
> cd third_party
> git clone https://github.com/google/googletest.git
> git clone -b v2.3 https://github.com/pybind/pybind11.git
> cd ..
> ```

This works for me
